import type { ComplaintCase, MinuteDocument, Poll, User } from "@/lib/types";

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const seedUsers: User[] = [
  {
    id: "user-staff-1",
    name: "Aarav Staff",
    email: "staff@neoconnect.local",
    password: "password123",
    role: "staff",
    department: "Operations",
  },
  {
    id: "user-secretariat-1",
    name: "Sana Secretariat",
    email: "secretariat@neoconnect.local",
    password: "password123",
    role: "secretariat",
    department: "Secretariat",
  },
  {
    id: "user-case-1",
    name: "Ravi Case Manager",
    email: "manager@neoconnect.local",
    password: "password123",
    role: "caseManager",
    department: "Facilities",
  },
  {
    id: "user-admin-1",
    name: "Ishita Admin",
    email: "admin@neoconnect.local",
    password: "password123",
    role: "admin",
    department: "IT",
  },
];

export const seedCases: ComplaintCase[] = [
  {
    id: "case-1",
    trackingId: "NEO-2026-001",
    title: "Lighting outage in parking area",
    description: "Parking bay lights have been out for three evenings, creating a safety concern for late-shift staff.",
    category: "Safety",
    department: "Operations",
    location: "Basement Parking",
    severity: "High",
    isAnonymous: false,
    submitterName: "Aarav Staff",
    submitterId: "user-staff-1",
    status: "Escalated",
    assignedToId: "user-case-1",
    assignedToName: "Ravi Case Manager",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
    assignedAt: daysAgo(11),
    reminderSentAt: daysAgo(4),
    escalatedAt: daysAgo(1),
    actionTaken: "Vendor dispatched and temporary flood lights installed.",
    impactChange: "Night shift staff now use the parking area safely while permanent repairs are completed.",
    notes: [
      {
        id: "note-1",
        authorId: "user-secretariat-1",
        authorName: "Sana Secretariat",
        body: "Case assigned for immediate review due to severity.",
        createdAt: daysAgo(11),
      },
    ],
  },
  {
    id: "case-2",
    trackingId: "NEO-2026-002",
    title: "Washroom maintenance issue",
    description: "Recurring leakage in the second-floor washroom requires a permanent fix.",
    category: "Facilities",
    department: "Operations",
    location: "Block B - Floor 2",
    severity: "Medium",
    isAnonymous: true,
    submitterName: "Anonymous",
    submitterId: "user-staff-1",
    status: "Resolved",
    assignedToId: "user-case-1",
    assignedToName: "Ravi Case Manager",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(7),
    assignedAt: daysAgo(17),
    firstResponseAt: daysAgo(15),
    resolutionSummary: "Plumbing line replaced and maintenance checklist added.",
    actionTaken: "Facilities team replaced the damaged pipe and scheduled weekly inspections.",
    impactChange: "Leakage has stopped and the floor remains usable throughout the week.",
    notes: [
      {
        id: "note-2",
        authorId: "user-case-1",
        authorName: "Ravi Case Manager",
        body: "Resolved after contractor visit. Monitoring for one week.",
        createdAt: daysAgo(7),
      },
    ],
  },
  {
    id: "case-3",
    trackingId: "NEO-2026-003",
    title: "Clarify hybrid work policy",
    description: "Staff are unclear on hybrid eligibility after the recent restructure.",
    category: "Policy",
    department: "HR",
    location: "Corporate Office",
    severity: "Low",
    isAnonymous: false,
    submitterName: "Aarav Staff",
    submitterId: "user-staff-1",
    status: "In Progress",
    assignedToId: "user-case-1",
    assignedToName: "Ravi Case Manager",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
    assignedAt: daysAgo(4),
    firstResponseAt: daysAgo(3),
    notes: [
      {
        id: "note-3",
        authorId: "user-case-1",
        authorName: "Ravi Case Manager",
        body: "Working with HR to publish updated guidance in the next bulletin.",
        createdAt: daysAgo(2),
      },
    ],
  },
  {
    id: "case-4",
    trackingId: "NEO-2026-004",
    title: "Air conditioning too cold on floor 4",
    description: "Temperature is consistently low enough to affect concentration.",
    category: "Facilities",
    department: "Finance",
    location: "HQ Floor 4",
    severity: "Low",
    isAnonymous: false,
    submitterName: "Aarav Staff",
    submitterId: "user-staff-1",
    status: "New",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    notes: [],
  },
  {
    id: "case-5",
    trackingId: "NEO-2026-005",
    title: "Repeated safety signage gaps",
    description: "Temporary contractor zones are missing warning signs during setup hours.",
    category: "Safety",
    department: "Operations",
    location: "Warehouse Corridor",
    severity: "High",
    isAnonymous: true,
    submitterName: "Anonymous",
    submitterId: "user-staff-1",
    status: "Assigned",
    assignedToId: "user-case-1",
    assignedToName: "Ravi Case Manager",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    assignedAt: daysAgo(2),
    notes: [],
  },
];

export const seedPolls: Poll[] = [
  {
    id: "poll-1",
    question: "Which improvement should be prioritised next quarter?",
    createdAt: daysAgo(3),
    createdById: "user-secretariat-1",
    createdByName: "Sana Secretariat",
    voters: ["user-staff-1"],
    options: [
      { id: "poll-1-opt-1", label: "Cafeteria seating", votes: 1 },
      { id: "poll-1-opt-2", label: "Commuter shuttle timing", votes: 0 },
      { id: "poll-1-opt-3", label: "Quiet work booths", votes: 0 },
    ],
  },
];

export const seedMinutes: MinuteDocument[] = [
  {
    id: "minutes-1",
    title: "Q1 Joint Consultative Committee Minutes",
    quarter: "Q1 2026",
    uploadedAt: daysAgo(10),
    uploadedById: "user-secretariat-1",
    uploadedByName: "Sana Secretariat",
    fileName: "sample-minutes-q1.pdf",
    url: "/uploads/sample-minutes-q1.pdf",
  },
];
